### ISSUE TITLE
consider not recommending `-Xcheckinit`

### ISSUE THREAD

**Issue by SethTisue** [DavidGregory084/sbt-tpolecat#10]
it has a performance cost, and lord knows whether it induces correctness issues or not

I would suggest you not recommend it here. personally I would only ever enable it temporarily, during troubleshooting

**Comment by DavidGregory084** [comment]
I don't know if I agree with this @SethTisue - debugging initialization order issues is one of the most frustrating things about Scala.

I'd rather find out where the root of the issue is straight away when I run my unit tests than have to enable it later after something silently goes wrong in production, and I don't think I'm alone in feeling that way.

**Comment by tpolecat** [comment]
Yeah I always have it on. It's a workaround for the worst bug in Scala and for me it's pretty essential.

**Comment by SethTisue** [comment]
okay, no consensus on this one I see :-)

**Comment by BalmungSan** [comment]
Would it be possible, somehow _(I don't know too much about **SBT**)_, that the flag is not used when building production artifacts?
Maybe trough a configuration flag?

**Comment by SethTisue** [comment]
yes. the details would depend on how the publishing aspect of your build is set up.

**Comment by BalmungSan** [comment]
I mean that, if it would be possible for the plugin itself to provide a simple and standard way to disable this flag.

Each project should be in charge of disabling it when building production artifacts.

**Comment by SethTisue** [comment]
Ah, I see. Well, that exceeds my own ambition level here.

**Comment by DavidGregory084** [comment]
@BalmungSan it's an interesting idea for sure. I think a lot of the community projects are under-utilising the Scala optimizer for this reason, for example.
