### ISSUE TITLE
Consider adding -Ywarn-macros:after

### ISSUE THREAD

**Issue by BalmungSan** [DavidGregory084/sbt-tpolecat#13]
This flag reduces a lot of false positives, especially when some implicits are used inside a macro expansion. **Circe** is a common case for such a problem.
Also, as far as I know, there is no downside on adding it.

**Comment by DavidGregory084** [comment]
Ah I wasn't aware of this flag, this is a great idea - my only question is whether it would be problematic to cause warnings in expanded macros since users cannot do anything about it? Perhaps -Wwarn-macros:none might be the best choice?

**Comment by BalmungSan** [comment]
That would not solve the first problem and would add extra problems.

The original problem is something like this:

```scala
import io.circe.Encoder
import io.circe.generic.semiauto.deriveEncoder
import io.circe.syntax._

final case class A(i: Int)
final case class B(name: String, a: A)

implicit val AEncoder: Encoder[A] = deriveEncoder
implicit val BEncoder: Encoder[B] = deriveEncoder

B(name = "Test", a = A(i = 10)).asJson.noSpaces
```

If you compile this snippet with the plugin. You would get an unused value warning for `AEncoder` which will be turn on an error. Thus, it would not compile.
The problem is that `AEncoder` is only used for the derivation of `BEncoder`, which happens inside a macro, that has not being expanded when the unused analysis is executed.
To solve it, you would have to manually add the **-Ywarn-macros:after** flag. So the check for unused values is executed after the macros had been expanded.

As far as I know, this should not cause problems to final users, unless the macro is leaving unused values _(I would hope that is uncommon)_. The only downside I see is, slower compilation times.

----------------------------------------------------

As I already said **-Ywarn-macros:none** would not only not solve this problems, but cause more.
Consider this code:

```scala
import com.typesafe.scalalogging.StrictLogging

object Main extends App with StrictLogging {
  val testMessage = "Hello, World!"
  logger.info(testMessage)
}
```

Since `testMessage` is only used inside the `logger.info` method, which is in turn a macro. It would be marked as an unused value.

**Comment by BalmungSan** [comment]
It seems there are [good reasons](https://github.com/scala/scala/pull/5876) _(at least from a theoretical point of view)_ for leaving **before** as the default.

**Comment by DavidGregory084** [comment]
In that case perhaps we should leave it as -Wmacros:before until such time as there is a -Wmacros:either option, which sounds like it would be the most ideal option here?

**Comment by BalmungSan** [comment]
@DavidGregory084 I think the better is to just leave it as it is right now. That way if a user needs it, he / she can just add the setting explicitly.

I may be nice if the plugin offers some way to activate / deactivate this one.
Maybe something like: `warnAfterMacros in tpolecat := true` but I am not sure how much of an improvement that would be.
_(unless a similar flag is also added for #10 then it would be worth adding this)_

**Comment by DavidGregory084** [comment]
OK, let's close this for now :+1:
