### ISSUE TITLE
Consider adding `-Wself-implicit`

### ISSUE THREAD

**Issue by Daenyth** [DavidGregory084/sbt-tpolecat#14]
This flag helps detect cases like `implicit val fooInstance: TC[Foo] = TC.apply[Foo]`

**Comment by DavidGregory084** [comment]
Thanks @Daenyth, haven't been writing Scala much recently and I hadn't noticed this was added!

**Comment by kubukoz** [comment]
I think the flag doesn't work correctly. See https://github.com/profunktor/console4cats/pull/65

**Comment by DavidGregory084** [comment]
Probably best to revert that for now then @kubukoz! I've raised https://github.com/scala/bug/issues/11813

**Comment by kubukoz** [comment]
Thanks a lot!

**Comment by som-snytt** [comment]
It's now a lint `implicit-recursion`.

https://github.com/scala/scala/blob/v2.13.3/src/compiler/scala/tools/nsc/settings/Warnings.scala#L192

**Comment by DavidGregory084** [comment]
Awesome, thanks @som-snytt - I think I'll leave for a few days to make sure compiler plugins are published before I add something that forces people to bump Scala version.

**Comment by dwijnand** [comment]
https://github.com/scala/bug/issues/11813 was fixed
