### ISSUE TITLE
`utf-8` should be `utf8`

### ISSUE THREAD

**Issue by Baccata** [DavidGregory084/sbt-tpolecat#17]
Hi, I'm not using your plugin but I am aware of its existence. 

I've recently been victim of this bug https://github.com/scalameta/metals/issues/1303 (as I'm using Rob Norris' flag list on every project). The bug was caused by a bad encoding value : `utf-8` should be `utf8`.  See[here](https://docs.scala-lang.org/overviews/compiler-options/index.html)

Kind regards

**Comment by DavidGregory084** [comment]
Thanks for the report @Baccata, this should be fixed in 0.1.11 thanks to @ybasket
