### ISSUE TITLE
Warn on unused parameters in 2.13

### ISSUE THREAD

**Issue by benwaffle** [DavidGregory084/sbt-tpolecat#18]
Looks like in scala 2.13, `-Ywarn-unused:params` has been replaced with `-Ywarn-unused:explicits`. Can we add it in?

**Comment by DavidGregory084** [comment]
Ah I wasn't aware this had changed @benwaffle, thanks for the report!

Looking at [the docs](https://docs.scala-lang.org/overviews/compiler-options/index.html), it seems like `-Wunused:params` has been split into `-Wunused:explicits` and `-Wunused:explicits`, but `-Wunused:params` still exists and enables both. Perhaps what we need to do is to remove `-Wunused:implicits` as it is already enabled by `-Wunused:params`?
