### ISSUE TITLE
Tut not found

### ISSUE THREAD

**Issue by dcsobral** [DavidGregory084/sbt-tpolecat#20]
README recommends this:

```scala
scalacOptions.in(Tut) ~= filterConsoleScalacOptions
```

please use some actual configuration? Also, I'd suggest switching to the `/` syntax.

**Comment by DavidGregory084** [comment]
Immediately above this the README says
```
f necessary you can filter out scalac options that are unhelpful in the REPL from user-defined tasks or scopes.
```
I can't posslbly predict what plugins and configurations the user will have. The code sample is just an example of such a user-defined scope.

I don't use SBT anymore and haven't regularly done so for about 3 years. If you'd like to keep this plugin up to date I am happy to give you maintainer access. Failing that, PRs are welcome.
