### ISSUE TITLE
Scala 2.13.3 removed `-Xlint:nullary-override`

### ISSUE THREAD

**Issue by anilkumarmyla** [DavidGregory084/sbt-tpolecat#24]
Attempting to use this plugin in projects with scala 2.13.3 will result in this error message

```
[error] 'nullary-override' is not a valid choice for '-Xlint'
```

**Comment by anilkumarmyla** [comment]
Seems like the plugin doesn't have a way to disable an option in a patch release of scala
```
    ScalacOption("-Xlint:nullary-override", addedIn = Some(11), removedIn = dotty),           // Warn when non-nullary `def f()' overrides nullary `def f'.
```

Any guidance on how this can be resolved?

**Comment by DavidGregory084** [comment]
Ah I see. I think the best thing to do would be to filter out this option for now:

```scala
scalaOptions ~= { opts => opts.filterNot(Set("-Xlint:nullary-override")) }
```

I will cut a new release shortly that removes this option for 2.13 as I expect most people will probably be able to use the most current point release without any issues. 

I generally don't make efforts to support old point releases of Scala in this plugin as I imagine that would be a pretty involved software archaeology project.

**Comment by anilkumarmyla** [comment]
Thanks for the clarification, I made #25 based on your suggestion. Please take a look
