### ISSUE TITLE
Mill support

### ISSUE THREAD

**Issue by ghostbuster91** [DavidGregory084/sbt-tpolecat#31]
I need to have something like that for Mill build tool.

How could we approach that problem? Is this something that you would consider merging into this repository or should I fork it?

**Comment by DavidGregory084** [comment]
@ghostbuster91 you may want to look at https://github.com/DavidGregory084/mill-tpolecat :)

**Comment by ghostbuster91** [comment]
Yep, I found it later that day, thanks :)
