### ISSUE TITLE
-explain-types generates far too much output

### ISSUE THREAD

**Issue by DavidGoodenough** [DavidGregory084/sbt-tpolecat#38]
I was trying to upgrade a project from scala-2 to -3, and having to do it manually (scala3-migrate was gagging on ScalaFX code).  The compiler was generating so much output (from code that compiled totally cleanly in Scala-2) and the explain-types code is so large compared to the actual error messages that I could not use a full screen console to see more than 1 error per scroll, and I think (unproven) that this was taking so long to generate and send that when metals trys to start sbt it times out.  

I know the compiler is trying to be helpful, but one does need to be able to see the wood for the trees!

Please remove this option (at least for now) along with -explain (both seen to be needed to be removed to clean up the output)

**Comment by DavidGregory084** [comment]
I don't have any objection @DavidGoodenough but I'd be interested to see if this opinion is more widely held. Perhaps we should ask on Scala Users?

In the meantime you can always do:

```scala
scalacOptions ~= { opts => opts.filterNot(_.startsWith("-explain")) }
```

**Comment by SethTisue** [comment]
I really don't think this flag was ever intended to be on by default.
