### ISSUE TITLE
Scala 2.13 support

### ISSUE THREAD

**Issue by gmethvin** [DavidGregory084/sbt-tpolecat#4]
It would be nice if this also worked on the latest milestone of Scala 2.13 (currently 2.13.0-M4). To make it work in my project I had to add:

```scala
scalacOptions in Compile := {
  val invalidOptions = CrossVersion.partialVersion(scalaVersion.value) match {
    case Some((2, 13)) => Set("-Yno-adapted-args", "-Ypartial-unification")
    case _ => Set.empty[String]
  }
  scalacOptions.value.filterNot(invalidOptions)
}
```

**Comment by DavidGregory084** [comment]
Ah, thanks for the reminder - I will try to have a look at this sometime over the next few days

**Comment by pathikrit** [comment]
See also: https://slideslive.com/38907975/migrating-to-scala-213

**Comment by DavidGregory084** [comment]
That's a great resource, thanks @pathikrit!

**Comment by DavidGregory084** [comment]
@gmethvin 0.1.4 is on Binary now:

* Updating sbt-partial-unification should ensure that the relevant option is removed on 2.13
* The only one of the options this plugin applies that is deprecated is `-Yno-adapted-args`
* I didn't see any new options in the [Compiler Options](https://docs.scala-lang.org/overviews/compiler-options/index.html) documentation that seemed like they could be applied universally
