### ISSUE TITLE
Unable to use `-source:3.0-migration`

### ISSUE THREAD

**Issue by majk-p** [DavidGregory084/sbt-tpolecat#43]
Using latest (`0.1.19`) version of the plugin, I cannot use `-source:3.0-migration` as the `-source future` flag is already added (since https://github.com/DavidGregory084/sbt-tpolecat/pull/42).

Example:
```scala
scalacOptions ++= {
  if (scalaVersion.value.startsWith("3."))
    Seq("-source:3.0-migration")
  else
    Seq()
}
```

Error:
```
[error] Flag -source set repeatedly
[error] one error found
[error] (core / Compile / compileIncremental) Compilation failed
[error] Total time: 0 s, completed May 30, 2021, 5:04:23 PM
```

@2m was right about https://github.com/DavidGregory084/sbt-tpolecat/pull/42#issuecomment-850388526

**Comment by kubukoz** [comment]
I think we should roll back the change for now. Later we can do something smarter like enabling `-source:future` in 3.x **and** `-source:3.0` in 2.13, but that'd still break 2.12 so probably letting users handle this on their own will be a saner option.

**Comment by kubukoz** [comment]
@m2 @DavidGregory084 wdyt?

**Comment by bplommer** [comment]
> Later we can do something smarter like enabling `-source:future` in 3.x **and** `-source:3.0` in 2.13, but that'd still break 2.12 so probably letting users handle this on their own will be a saner option.



> I think we should roll back the change for now. Later we can do something smarter like enabling `-source:future` in 3.x **and** `-source:3.0` in 2.13, but that'd still break 2.12 so probably letting users handle this on their own will be a saner option.
> 
> btw. for future reference, one can use `scalacOptions --= Seq("source", "future")` before setting their own override in such cases like this.



> I think we should roll back the change for now. Later we can do something smarter like enabling `-source:future` in 3.x **and** `-source:3.0` in 2.13, but that'd still break 2.12

2.12.14 has `-source:3.0` - is there something missing from it that 2.13.6 has?
