### ISSUE TITLE
-Vtype-diffs is terrible, can we remove it?

### ISSUE THREAD

**Issue by tpolecat** [DavidGregory084/sbt-tpolecat#45]
I really really hate the output from `-Vtype-diffs` (as does everyone I have talked to about it) and suggest we remove it as a default option.

**Comment by DavidGregory084** [comment]
This pairs up pretty well with #38 - I don't have any objections personally

**Comment by SethTisue** [comment]
I agree that it's not appropriate for this to be on by default.

**Comment by dwijnand** [comment]
-X is experimental and -Y is even more so, is what I gathered.

Seeing as the hate is really really fresh, what could be improved?  Is it the verbosity (mentioned in #38) or something else?

**Comment by kubukoz** [comment]
Personally I think this is good to have in places where you have distinguishible colors, but it's really unhelpful in Metals and Bloop:

<img width="1694" alt="image" src="https://user-images.githubusercontent.com/894884/148142872-c38a13c6-bbdb-47a9-8602-1064d0e00aee.png">

<img width="1228" alt="image" src="https://user-images.githubusercontent.com/894884/148142882-a4fbd1b3-5d5d-4677-97b5-9d2981523def.png">

**Comment by DavidGregory084** [comment]
Resolved in #51
