### ISSUE TITLE
Tag release version in git?

### ISSUE THREAD

**Issue by anilkumarmyla** [DavidGregory084/sbt-tpolecat#6]
Often times we rely on git-tag-release as a notification that a new version of the software is available. Most of the github project follow this convention

**Comment by DavidGregory084** [comment]
Ah, I thought most people used sbt-updates for that. I can set up tags, no problem.

**Comment by DavidGregory084** [comment]
Each released version should have a tag now, hope that helps

**Comment by anilkumarmyla** [comment]
thanks!
