### ISSUE TITLE
please don't recommend `-Xfuture`

### ISSUE THREAD

**Issue by SethTisue** [DavidGregory084/sbt-tpolecat#9]
see my remarks about it (and its sibling `-Xsource:...`) at https://github.com/scala/bug/issues/11661

**Comment by DavidGregory084** [comment]
This seems reasonable to me @SethTisue, I think the community understood this to mean "give me warnings for bits of my code which will change in upcoming releases", and it seems that is not what `-Xfuture` is.

**Comment by SethTisue** [comment]
>  I think the community understood this to mean "give me warnings for bits of my code which will change in upcoming releases", and it seems that is not what -Xfuture is.

(as an aside, some versions ago we had `-Xmigration` for that, perhaps we could revive that in 2.13.x or 2.14)
